-- nhansu.ctl

OPTIONS (SKIP=1)

-- Load data into NHANSU table
LOAD DATA
CHARACTERSET UTF8
INFILE 'data/nhansu.csv'
APPEND INTO TABLE NHANSU
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  MANV CHAR,
  HOTEN CHAR,
  PHAI CHAR,
  NGSINH DATE "YYYY-MM-DD",
  PHUCAP INTEGER EXTERNAL,
  DT CHAR,
  VAITRO CHAR,
  MADV CHAR
)