-- CS#1
CREATE OR REPLACE VIEW V_INFO_NHANSU
AS
    SELECT *
    FROM QLTRUONGHOC.NHANSU
    WHERE TRIM(UPPER(MANV)) = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON V_INFO_NHANSU TO NHANVIEN;
GRANT UPDATE(DT) ON V_INFO_NHANSU TO NHANVIEN;
/
GRANT SELECT ON QLTRUONGHOC.SINHVIEN TO NHANVIEN;
GRANT SELECT ON QLTRUONGHOC.DONVI TO NHANVIEN;
GRANT SELECT ON QLTRUONGHOC.HOCPHAN TO NHANVIEN;
GRANT SELECT ON QLTRUONGHOC.KHMO TO NHANVIEN;
/
-- CS#2
GRANT NHANVIEN TO GIANGVIEN;
/
CREATE OR REPLACE VIEW V_INFO_PHANCONG
AS
    SELECT *
    FROM QLTRUONGHOC.PHANCONG
    WHERE TRIM(UPPER(MAGV)) = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON V_INFO_PHANCONG TO GIANGVIEN;
/
CREATE OR REPLACE VIEW V_INFO_LOPPHANCONG
AS
    SELECT *
    FROM QLTRUONGHOC.DANGKY
    WHERE TRIM(UPPER(MAGV)) = SYS_CONTEXT('USERENV', 'SESSION_USER');
    
GRANT SELECT ON V_INFO_LOPPHANCONG TO GIANGVIEN;
/
GRANT UPDATE(DIEMTH,DIEMQT,DIEMCK,DIEMTK) ON V_INFO_LOPPHANCONG TO GIANGVIEN;
/
-- CS#3
GRANT NHANVIEN TO GIAOVU;
commit
