ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- tạo schema mới
--- Xoá nếu nó đã tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLTRUONGHOC CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -01918 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/
GRANT DBA, SET CONTAINER, LBAC_DBA TO QLTRUONGHOC IDENTIFIED BY 123123;
GRANT ALL PRIVILEGES TO QLTRUONGHOC;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;
/
COMMIT;