ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
show pdbs
-- Đổi sang pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;

-- Bật tính năng OLS
-- This procedure registers Oracle Label Security.
EXEC LBACSYS.CONFIGURE_OLS;
-- This procedure enables it.
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;


-- Tạo admin user, người sẽ cài đặt OLS
GRANT DBA, SET CONTAINER, LBAC_DBA TO ols_quocbao IDENTIFIED BY pwd;


-- Connect vào tài khoản admin OLS
CONNECT OLS_QUOCBAO@XEPDB1;

-- Xóa bảng THONGBAO nếu đã tồn tại
BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE = -942 THEN
            NULL; -- Bảng không tồn tại, không cần làm gì
         ELSE
            RAISE; -- Các lỗi khác, báo lỗi
         END IF;
END;
/
-- Tạo bảng
CREATE TABLE THONGBAO (
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOIDUNG NVARCHAR2(2000)
);

-- Xóa các role nếu đã tồn tại
DROP ROLE TRUONGKHOA;
DROP ROLE TRUONGDONVI;
DROP ROLE GIANGVIEN;
DROP ROLE GIAOVU;
DROP ROLE NHANVIEN;
DROP ROLE SINHVIEN;

-- Tạo roles
CREATE ROLE TRUONGKHOA;
CREATE ROLE TRUONGDONVI;
CREATE ROLE GIANGVIEN;
CREATE ROLE GIAOVU;
CREATE ROLE NHANVIEN;
CREATE ROLE SINHVIEN;

-- Trao quyền SELECT 
GRANT SELECT ON THONGBAO TO TRUONGKHOA, TRUONGDONVI, GIANGVIEN, GIAOVU, NHANVIEN, SINHVIEN;

-- Xoá các user nếu đã tồn tại
DROP USER TKhoa633 CASCADE;
DROP USER TDonVi081 CASCADE;
DROP USER TDonVi082 CASCADE;
DROP USER GVien401 CASCADE;
DROP USER GVien402 CASCADE;
DROP USER GVu011 CASCADE;
DROP USER NVien122 CASCADE;
DROP USER SVien321 CASCADE;
DROP USER SVien322 CASCADE;

-- Tạo và gán quyền cho các user để test chức năng --

-- Trưởng khoa 
GRANT CONNECT, TRUONGKHOA TO TKhoa633 IDENTIFIED BY pwd;
-- Trưởng đơn vị KHMT cơ sở 1
GRANT CONNECT, TRUONGDONVI TO TDonVi081 IDENTIFIED BY pwd;
-- Trưởng đơn vị KHMT cơ sở 2
GRANT CONNECT, TRUONGDONVI TO TDonVi082 IDENTIFIED BY pwd;
-- Giảng viên khoa HTTT và KHMT cơ sở 1
GRANT CONNECT, GIANGVIEN TO GVien401 IDENTIFIED BY pwd;
-- Giảng viên khoa HTTT và KHMT cơ sở 2
GRANT CONNECT, GIANGVIEN TO GVien402 IDENTIFIED BY pwd;
-- Giáo vụ khoa MMT cơ sở 1
GRANT CONNECT, GIAOVU TO GVu011 IDENTIFIED BY pwd;
-- Nhân viên khoa KHMT và CNTT
GRANT CONNECT, NHANVIEN TO NVien122 IDENTIFIED BY pwd;
-- Sinh viên khoa HTTT cơ sở 1
GRANT CONNECT, SINHVIEN TO SVien321 IDENTIFIED BY pwd;
-- Sinh viên khoa HTTT cơ sở 2
GRANT CONNECT, SINHVIEN TO SVien322 IDENTIFIED BY pwd;


-- Tạo OLS policy container

BEGIN
 SA_SYSDBA.CREATE_POLICY (
  policy_name      => 'THONGBAO_OLS_POL',
  column_name      => 'OLS_COL');
END;
/


-- Kích hoạt policy
EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_OLS_POL');

-- Gán quyền quản lý policy cho admin OLS
CONNECT SYS AS SYSDBA;
ALTER SESSION SET CONTAINER = XEPDB1;
GRANT THONGBAO_OLS_POL_DBA TO OLS_QUOCBAO;

-- Commit các thay đổi trước khi re-start database
COMMIT;

SHUTDOWN IMMEDIATE;
STARTUP;

-- Trở lại người dùng admin OLS
CONNECT OLS_QUOCBAO@XEPDB1;

ALTER SESSION SET CONTAINER = XEPDB1;

-- Tạo các component trong OLS policy ---

-- Levels
BEGIN
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 60,
      short_name  => 'TS',
      long_name   => 'TOP_SECRET');

   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 50,
      short_name  => 'S',
      long_name   => 'SECRET');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 40,
      short_name  => 'C',
      long_name   => 'CONFIDENTIAL');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 30,
      short_name  => 'R',
      long_name   => 'RESTRICTED');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 20,
      short_name  => 'I',
      long_name   => 'INTERNAL_USE');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 10,
      short_name  => 'P',
      long_name   => 'PUBLIC');
END;
/

-- Compartments
BEGIN
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'HE_THONG_THONG_TIN',
    short_name       => 'HTTT',
    comp_num         =>  6000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'CONG_NGHE_PHAN_MEM',
    short_name       => 'CNPM',
    comp_num         =>  5000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'KHOA_HOC_MAY_TINH',
    short_name       => 'KHMT',
    comp_num         =>  4000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'CONG_NGHE_TRI_THUC',
    short_name       => 'CNTT',
    comp_num         =>  3000);

  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'THI_GIAC_MAY_TINH',
    short_name       => 'TGMT',
    comp_num         =>  2000);

  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'MANG_MAY_TINH',
    short_name       => 'MMT',
    comp_num         =>  1000);
END;
/

-- Groups
BEGIN
  -- Parent group
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 3000,
   short_name      => 'TT',
   long_name       => 'TOAN_TRUONG');
  
  -- Child groups
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 2000,
   short_name      => 'CS1',
   long_name       => 'CO_SO_1',
   parent_name     => 'TT');
   
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 1000,
   short_name      => 'CS2',
   long_name       => 'CO_SO_2',
   parent_name     => 'TT'); 
END;
/

-- Tạo data lables --
BEGIN
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 8192,
      label_value  => 'TS::',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4101,
      label_value  => 'S:MMT:CS2',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4106,
      label_value  => 'S:TGMT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1029,
      label_value  => 'R:MMT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1153,
      label_value  => 'R:HTTT:CS2',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4096,
      label_value  => 'S::',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 386,
      label_value  => 'P:HTTT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 385,
      label_value  => 'P:HTTT:CS2',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4130,
      label_value  => 'S:KHMT:CS1',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4129,
      label_value  => 'S:KHMT:CS2',
      data_label   => TRUE);
      
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4128,
      label_value  => 'S:KHMT:',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1026,
      label_value  => 'R::CS1',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 2208,
      label_value  => 'C:HTTT,KHMT:',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 561,
      label_value  => 'I:KHMT,CNTT:CS2',
      data_label   => TRUE);
      
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 384,
      label_value  => 'P:HTTT:',
      data_label   => TRUE);
END;
/

-- Gán label cho user --
BEGIN
   -- a) 
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'Tkhoa633', 
      max_read_label => 'TS:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- b)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'TDonVi082', 
      max_read_label => 'S:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- c)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVu011', 
      max_read_label => 'R:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
  
   ------
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'TDonVi081', 
      max_read_label => 'S:KHMT:CS1');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVien401', 
      max_read_label => 'C:HTTT,KHMT:CS1');

   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'SVien321', 
      max_read_label => 'P:HTTT:CS1');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NVien122', 
      max_read_label => 'I:KHMT,CNTT:CS2');  
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'SVien322', 
      max_read_label => 'P:HTTT:CS2');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVien402', 
      max_read_label => 'C:HTTT,KHMT:CS2');
END;
/

-- Áp dụng OLS policy và OLS_QUOCBAO schema ---
BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name    => 'THONGBAO_OLS_POL',
    schema_name    => 'OLS_QUOCBAO', 
    table_name     => 'THONGBAO',
    table_options  => 'READ_CONTROL');
END;
/

-- Kích hoạt policy
BEGIN
   SA_POLICY_ADMIN.ENABLE_TABLE_POLICY (
      policy_name => 'THONGBAO_OLS_POL',
      schema_name => 'OLS_QUOCBAO',
      table_name  => 'THONGBAO');
END;
/

-- Insert dữ liệu
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng khoa [...]', 8192);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị khoa MMT cơ sở 2 [...]', 4101);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị khoa TGMT cơ sở 1 [...]', 4106);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Giáo vụ khoa MMT cơ sở 1 [...]', 1029);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Giáo vụ khoa HTTT cơ sở 2 [...]', 1153);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Trưởng đơn vị [...]', 4096);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Sinh viên ngành HTTT cơ sở 1 [...]', 386);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Sinh viên ngành HTTT cơ sở 2 [...]', 385);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị KHMT cơ sở 1 [...]', 4130);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị KHMT cơ sở 2 [...]', 4129);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Trưởng đơn vị KHMT [...]', 4128);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Giáo vụ cơ sở 1 [...]', 1026);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Giảng viên khoa HTTT và KHMT [...]', 2208);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Nhân viên khoa KHMT và CNTT ở cơ sở 2 [...]', 561);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Sinh viên ngành HTTT [...]', 384);

COMMIT;

ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;