ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Đổi sang pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;

-- Bật tính năng OLS
-- This procedure registers Oracle Label Security.
EXEC LBACSYS.CONFIGURE_OLS;
-- This procedure enables it.
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;


-- Tạo admin user, người sẽ cài đặt OLS
--GRANT DBA, SET CONTAINER, LBAC_DBA TO ols_quocbao IDENTIFIED BY pwd;
GRANT DBA, SET CONTAINER, LBAC_DBA TO QLTRUONGHOC IDENTIFIED BY 123123;
CREATE USER QLTRUONGHOC IDENTIFIED BY 123123;
GRANT ALL PRIVILEGES TO QLTRUONGHOC;

-- Connect vào tài khoản admin OLS
CONNECT OLS_QUOCBAO@XEPDB1;

-- Xóa bảng THONGBAO nếu đã tồn tại
BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE = -942 THEN
            NULL; -- Bảng không tồn tại, không cần làm gì
         ELSE
            RAISE; -- Các lỗi khác, báo lỗi
         END IF;
END;
/
-- Tạo bảng
CREATE TABLE THONGBAO (
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOIDUNG NVARCHAR2(2000)
);

-- Xóa các role nếu đã tồn tại
DROP ROLE TRUONGKHOA;
DROP ROLE TRUONGDONVI;
DROP ROLE GIANGVIEN;
DROP ROLE GIAOVU;
DROP ROLE NHANVIEN;
DROP ROLE SINHVIEN;

-- Tạo roles
CREATE ROLE TRUONGKHOA;
CREATE ROLE TRUONGDONVI;
CREATE ROLE GIANGVIEN;
CREATE ROLE GIAOVU;
CREATE ROLE NHANVIEN;
CREATE ROLE SINHVIEN;

-- Trao quyền SELECT 
GRANT SELECT ON THONGBAO TO TRUONGKHOA, TRUONGDONVI, GIANGVIEN, GIAOVU, NHANVIEN, SINHVIEN;

-- Xoá các user nếu đã tồn tại
DROP USER TKhoa633 CASCADE;
DROP USER TDonVi081 CASCADE;
DROP USER TDonVi082 CASCADE;
DROP USER GVien401 CASCADE;
DROP USER GVien402 CASCADE;
DROP USER GVu011 CASCADE;
DROP USER NVien122 CASCADE;
DROP USER SVien321 CASCADE;
DROP USER SVien322 CASCADE;

-- Tạo và gán quyền cho các user để test chức năng --

-- Trưởng khoa 
GRANT CONNECT, TRUONGKHOA TO TKhoa633 IDENTIFIED BY pwd;
-- Trưởng đơn vị KHMT cơ sở 1
GRANT CONNECT, TRUONGDONVI TO TDonVi081 IDENTIFIED BY pwd;
-- Trưởng đơn vị KHMT cơ sở 2
GRANT CONNECT, TRUONGDONVI TO TDonVi082 IDENTIFIED BY pwd;
-- Giảng viên khoa HTTT và KHMT cơ sở 1
GRANT CONNECT, GIANGVIEN TO GVien401 IDENTIFIED BY pwd;
-- Giảng viên khoa HTTT và KHMT cơ sở 2
GRANT CONNECT, GIANGVIEN TO GVien402 IDENTIFIED BY pwd;
-- Giáo vụ khoa MMT cơ sở 1
GRANT CONNECT, GIAOVU TO GVu011 IDENTIFIED BY pwd;
-- Nhân viên khoa KHMT và CNTT
GRANT CONNECT, NHANVIEN TO NVien122 IDENTIFIED BY pwd;
-- Sinh viên khoa HTTT cơ sở 1
GRANT CONNECT, SINHVIEN TO SVien321 IDENTIFIED BY pwd;
-- Sinh viên khoa HTTT cơ sở 2
GRANT CONNECT, SINHVIEN TO SVien322 IDENTIFIED BY pwd;


-- Tạo OLS policy container

BEGIN
 SA_SYSDBA.CREATE_POLICY (
  policy_name      => 'THONGBAO_OLS_POL',
  column_name      => 'OLS_COL');
END;
/

BEGIN
 SA_SYSDBA.DROP_POLICY (
  policy_name      => 'THONGBAO_OLS_POL');
END;
/


-- Kích hoạt policy
EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_OLS_POL');

-- Gán quyền quản lý policy cho admin OLS
CONNECT SYS AS SYSDBA;
ALTER SESSION SET CONTAINER = XEPDB1;
--GRANT THONGBAO_OLS_POL_DBA TO OLS_QUOCBAO;
GRANT THONGBAO_OLS_POL_DBA TO QLTRUONGHOC;
-- Commit các thay đổi trước khi re-start database
COMMIT;

SHUTDOWN IMMEDIATE;
STARTUP;

-- Trở lại người dùng admin OLS
CONNECT OLS_QUOCBAO@XEPDB1;

ALTER SESSION SET CONTAINER = XEPDB1;

-- Tạo các component trong OLS policy ---

-- Levels
BEGIN
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 60,
      short_name  => 'TS',
      long_name   => 'TOP_SECRET');

   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 50,
      short_name  => 'S',
      long_name   => 'SECRET');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 40,
      short_name  => 'C',
      long_name   => 'CONFIDENTIAL');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 30,
      short_name  => 'R',
      long_name   => 'RESTRICTED');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 20,
      short_name  => 'I',
      long_name   => 'INTERNAL_USE');
      
   SA_COMPONENTS.CREATE_LEVEL (
      policy_name => 'THONGBAO_OLS_POL',
      level_num   => 10,
      short_name  => 'P',
      long_name   => 'PUBLIC');
END;
/


-- Compartments
BEGIN
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'HE_THONG_THONG_TIN',
    short_name       => 'HTTT',
    comp_num         =>  6000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'CONG_NGHE_PHAN_MEM',
    short_name       => 'CNPM',
    comp_num         =>  5000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'KHOA_HOC_MAY_TINH',
    short_name       => 'KHMT',
    comp_num         =>  4000);
    
  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'CONG_NGHE_TRI_THUC',
    short_name       => 'CNTT',
    comp_num         =>  3000);

  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'THI_GIAC_MAY_TINH',
    short_name       => 'TGMT',
    comp_num         =>  2000);

  SA_COMPONENTS.CREATE_COMPARTMENT (
    policy_name      => 'THONGBAO_OLS_POL',
    long_name        => 'MANG_MAY_TINH',
    short_name       => 'MMT',
    comp_num         =>  1000);
END;
/

-- Groups
BEGIN
  -- Parent group
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 3000,
   short_name      => 'TT',
   long_name       => 'TOAN_TRUONG');
  
  -- Child groups
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 2000,
   short_name      => 'CS1',
   long_name       => 'CO_SO_1',
   parent_name     => 'TT');
   
  SA_COMPONENTS.CREATE_GROUP (
   policy_name     => 'THONGBAO_OLS_POL',
   group_num       => 1000,
   short_name      => 'CS2',
   long_name       => 'CO_SO_2',
   parent_name     => 'TT'); 
END;
/

-- Tạo data lables --
BEGIN
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 8192,
      label_value  => 'TS::',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4101,
      label_value  => 'S:MMT:CS2',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4106,
      label_value  => 'S:TGMT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1029,
      label_value  => 'R:MMT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1153,
      label_value  => 'R:HTTT:CS2',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4096,
      label_value  => 'S::',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 386,
      label_value  => 'P:HTTT:CS1',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 385,
      label_value  => 'P:HTTT:CS2',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4130,
      label_value  => 'S:KHMT:CS1',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4129,
      label_value  => 'S:KHMT:CS2',
      data_label   => TRUE);
      
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 4128,
      label_value  => 'S:KHMT:',
      data_label   => TRUE);
   
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 1026,
      label_value  => 'R::CS1',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 2208,
      label_value  => 'C:HTTT,KHMT:',
      data_label   => TRUE);
       
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 561,
      label_value  => 'I:KHMT,CNTT:CS2',
      data_label   => TRUE);
      
   SA_LABEL_ADMIN.CREATE_LABEL (
      policy_name  => 'THONGBAO_OLS_POL',
      label_tag    => 384,
      label_value  => 'P:HTTT:',
      data_label   => TRUE);
END;
/

-- Gán label cho user --
BEGIN
   -- a) 
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'Tkhoa633', 
      max_read_label => 'TS:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- b)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'TDonVi082', 
      max_read_label => 'S:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- c)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVu011', 
      max_read_label => 'R:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
  
   ------
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'TDonVi081', 
      max_read_label => 'S:KHMT:CS1');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVien401', 
      max_read_label => 'C:HTTT,KHMT:CS1');

   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'SVien321', 
      max_read_label => 'P:HTTT:CS1');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NVien122', 
      max_read_label => 'I:KHMT,CNTT:CS2');  
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'SVien322', 
      max_read_label => 'P:HTTT:CS2');
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'GVien402', 
      max_read_label => 'C:HTTT,KHMT:CS2');
END;
/


BEGIN
   -- a) 
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NV0005', 
      max_read_label => 'TS:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- b)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NV0004', 
      max_read_label => 'S:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
   -- c)
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NV0003', 
      max_read_label => 'R:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:TT');
  
   ------

      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NV0002', 
      max_read_label => 'C:HTTT,KHMT:CS1');

      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'NV0001', 
      max_read_label => 'I:KHMT,CNTT:CS2');  
      
   SA_USER_ADMIN.SET_USER_LABELS (
      policy_name    => 'THONGBAO_OLS_POL',
      user_name      => 'SV0001', 
      max_read_label => 'P:HTTT:CS2');
      
  
END;
/




-- Áp dụng OLS policy và OLS_QUOCBAO schema ---
--BEGIN
--  SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
--    policy_name    => 'THONGBAO_OLS_POL',
--    schema_name    => 'OLS_QUOCBAO', 
--    table_name     => 'THONGBAO',
--    table_options  => 'READ_CONTROL');
--END;
--/

BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name    => 'THONGBAO_OLS_POL',
    schema_name    => 'QLTRUONGHOC', 
    table_name     => 'THONGBAO',
    table_options  => 'READ_CONTROL');
END;
/

-- Kích hoạt policy
--BEGIN
--   SA_POLICY_ADMIN.ENABLE_TABLE_POLICY (
--      policy_name => 'THONGBAO_OLS_POL',
--      schema_name => 'OLS_QUOCBAO',
--      table_name  => 'THONGBAO');
--END;
--/
BEGIN
   SA_POLICY_ADMIN.ENABLE_TABLE_POLICY (
      policy_name => 'THONGBAO_OLS_POL',
      schema_name => 'QLTRUONGHOC',
      table_name  => 'THONGBAO');
END;
/

-- Insert dữ liệu
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng khoa [...]', 8192);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị khoa MMT cơ sở 2 [...]', 4101);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị khoa TGMT cơ sở 1 [...]', 4106);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Giáo vụ khoa MMT cơ sở 1 [...]', 1029);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Giáo vụ khoa HTTT cơ sở 2 [...]', 1153);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Trưởng đơn vị [...]', 4096);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Sinh viên ngành HTTT cơ sở 1 [...]', 386);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Sinh viên ngành HTTT cơ sở 2 [...]', 385);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị KHMT cơ sở 1 [...]', 4130);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Trưởng đơn vị KHMT cơ sở 2 [...]', 4129);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Trưởng đơn vị KHMT [...]', 4128);

INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Giáo vụ cơ sở 1 [...]', 1026);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Giảng viên khoa HTTT và KHMT [...]', 2208);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho Nhân viên khoa KHMT và CNTT ở cơ sở 2 [...]', 561);
INSERT INTO THONGBAO(NOIDUNG, OLS_COL) VALUES ('Thông báo dành cho tất cả Sinh viên ngành HTTT [...]', 384);

COMMIT;


--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- tạo schema mới
--- Xoá nếu nó đã tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLTRUONGHOC CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -01918 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/
CREATE USER QLTRUONGHOC IDENTIFIED BY 123123;
GRANT ALL PRIVILEGES TO QLTRUONGHOC;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;
/
conn QLTRUONGHOC/123123;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET CURRENT_SCHEMA = QLTRUONGHOC;
/
--- drop all table
DECLARE
    TYPE table_array IS VARRAY(7) OF VARCHAR2(30);
    v_table_names table_array := table_array('NHANSU', 'SINHVIEN', 'DONVI', 'HOCPHAN', 'KHMO', 'PHANCONG', 'DANGKY');
    v_sql        VARCHAR2(100);
BEGIN
    FOR i IN 1 .. v_table_names.COUNT LOOP
        BEGIN
            v_sql := 'DROP TABLE ' || v_table_names(i) || ' CASCADE CONSTRAINTS';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/
--- create table
CREATE TABLE NHANSU
(
    MANV VARCHAR2(6) NOT NULL,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(3)CONSTRAINT CHK_PHAI CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR2(10),
    VAITRO NVARCHAR2(20) CONSTRAINT CHK_VAITRO CHECK (VAITRO IN ('Nhân viên cơ bản', 'Giảng viên', 'Giáo vụ', 'Trưởng đơn vị', 'Trưởng khoa')),
    MADV VARCHAR2(6),
    CONSTRAINT PK_NS
    PRIMARY KEY(MANV)
);

CREATE TABLE SINHVIEN
(
    MASV VARCHAR2(6) NOT NULL,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(3) CONSTRAINT CHK_PHAI2 CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT VARCHAR2(10),
    MACT VARCHAR2(6),
    MANGANH VARCHAR2(6),
    SOTCTL INT,
    DTBTL FLOAT,
    CONSTRAINT PK_SV
    PRIMARY KEY(MASV)
);

CREATE TABLE DONVI
(
    MADV VARCHAR2(6) NOT NULL,
    TENDV NVARCHAR2(30),
    TRGDV VARCHAR2(6),
    CONSTRAINT PK_DV
    PRIMARY KEY(MADV),
    CONSTRAINT FK_TRGDV
    FOREIGN KEY(TRGDV) REFERENCES NHANSU(MANV)
);

CREATE TABLE HOCPHAN
(
    MAHP VARCHAR2(6) NOT NULL,
    TENHP NVARCHAR2(30),
    SOTC INT,
    STLT INT,
    STTH INT,
    SOSVTD INT,
    MADV VARCHAR2(6),
    CONSTRAINT PK_HP
    PRIMARY KEY(MAHP),
    CONSTRAINT FK_DVPHUTRACH
    FOREIGN KEY(MADV) REFERENCES DONVI(MADV)  
);

CREATE TABLE KHMO
(
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    CONSTRAINT PK_KHMO
    PRIMARY KEY(MAHP,HK,NAM,MACT),
    CONSTRAINT FK_HPMO
    FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
);

CREATE TABLE PHANCONG 
(
    MAGV VARCHAR2(6) NOT NULL,
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    CONSTRAINT PK_PHANCONG
    PRIMARY KEY(MAGV,MAHP,HK,NAM,MACT),
    CONSTRAINT FK_PHANCONG_GV
    FOREIGN KEY(MAGV) REFERENCES NHANSU(MANV),
    CONSTRAINT FK_PHANCONG_KHMO
    FOREIGN KEY(MAHP,HK,NAM,MACT) REFERENCES KHMO(MAHP,HK,NAM,MACT)
    
);

CREATE TABLE DANGKY
(
    MASV VARCHAR2(6) NOT NULL,
    MAGV VARCHAR2(6) NOT NULL,
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    CONSTRAINT PK_DANGKY
    PRIMARY KEY(MASV,MAGV,MAHP,HK,NAM,MACT),
    CONSTRAINT FK_DANGKY_SV
    FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_PHANCONG
    FOREIGN KEY(MAGV,MAHP,HK,NAM,MACT) REFERENCES PHANCONG(MAGV,MAHP,HK,NAM,MACT)
)
------ các ràng buộc toàn vẹn



----- Add data from csv

INSERT ALL 
INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV0001', 'Trương Hoàng Nhân', 'Nam', TO_DATE('17-08-2003', 'DD-MM-YYYY'), 'KTX Khu B', '0971641280', 'ĐT', 'CNTT' ,120, 8.0)
INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV0002', 'Nguyễn Văn A', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 'KTX Khu B', '0971641282', 'ĐT','CNTT', 120, 7.1)
SELECT * FROM dual;

INSERT ALL
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0001', 'Nguyễn Quang Định', 'Nữ', TO_DATE('01-01-1971', 'DD-MM-YYYY'), 10000, '0971641280','Nhân viên cơ bản' ,'VPK')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0002', 'Trương Kim Liên', 'Nữ', TO_DATE('01-01-1971', 'DD-MM-YYYY'), 10000, '0971641280','Giảng viên' ,'CNPM')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0003', 'Lưu Kiến Đạt', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Giáo vụ', 'VPK')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0004', 'Lê Viết Đạt Trọng', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Trưởng đơn vị', 'HTTT')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0005', 'Nguyễn Văn A', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Trưởng khoa', 'KHMT')
SELECT * FROM dual;

-- DONVI
INSERT ALL
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('CNPM', 'Công nghệ phần mềm', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('HTTT', 'Hệ thống thông tin', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('KHMT', 'Khoa học máy tính', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('MMT', 'Mạng máy tính và viễn thông', 'NV0004')
SELECT * FROM dual;

--HOCPHAN
INSERT ALL
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC001', 'Cơ sở dữ liệu', 4, 11, 0, 80 ,'HTTT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC002', 'Phát triển ứng dụng Web', 4, 11, 0, 80 ,'CNPM')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC003', 'Nhập môn khoa học dữ liệu', 4, 11, 0, 80 ,'KHMT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC004', 'Lập trình hướng đối tượng', 4, 11, 0, 80 ,'CNPM')
SELECT * FROM dual;
INSERT ALL
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC006', 'Phương pháp tính', 4, 11, 0, 80 ,'HTTT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC007', 'Đại số tuyến tính', 4, 11, 0, 80 ,'CNPM')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC008', 'Nhập môn lập trình', 4, 11, 0, 80 ,'KHMT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC009', 'Kỹ thuật lập trình', 4, 11, 0, 80 ,'CNPM')
SELECT * FROM dual;


--KHMO
INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC001', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC002', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC003', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC004', 1, 2024, 'ĐT')
SELECT * FROM dual;
INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC006', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC007', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC008', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC009', 1, 2024, 'ĐT')
SELECT * FROM dual;

INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC006', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC007', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC008', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC009', 2, 2024, 'ĐT')
SELECT * FROM dual;

--PHANCONG
INSERT ALL
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC001', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC002', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC003', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC004', 1, 2024, 'ĐT')
SELECT * FROM dual;

INSERT ALL
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC006', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC007', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC008', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC009', 1, 2024, 'ĐT')
SELECT * FROM dual;

--DANGKY
INSERT ALL
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC001',1 ,2024, 'ĐT', 10 ,10,10,10)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC002',1 ,2024, 'ĐT', 9 ,9,9,9)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC003', 1,2024, 'ĐT', 10 ,9,9,10)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC004', 1,2024, 'ĐT', 10 ,9.5,9.5,10)
SELECT * FROM dual;

/
CREATE OR REPLACE PROCEDURE CREATEUSER_TABLE_SINHVIEN
AS
    CURSOR CUR IS (SELECT MASV
                    FROM QLTRUONGHOC.SINHVIEN
                    WHERE MASV NOT IN (SELECT USERNAME
                                        		      FROM ALL_USERS)
                    );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET CONTAINER = XEPDB1';
    EXECUTE IMMEDIATE(STRSQL);
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
            
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR || ' container=current';
        EXECUTE IMMEDIATE STRSQL;
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE STRSQL;
    END LOOP;
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    CLOSE CUR;
END;
/

EXECUTE CREATEUSER_TABLE_SINHVIEN;
/


GRANT SINHVIEN TO SV0001;
--GRANT ALL PRIVILEGES TO SV0001; 

---------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE CREATEUSER_TABLE_NHANSU
AS
    CURSOR CUR IS (SELECT MANV
                    FROM NHANSU
                    WHERE MANV NOT IN (SELECT USERNAME
                                        		      FROM ALL_USERS)
                    );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET CONTAINER = XEPDB1';
    EXECUTE IMMEDIATE(STRSQL);
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
            
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR || ' container=current';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE CUR;
END;
/
EXECUTE CREATEUSER_TABLE_NHANSU;
GRANT NHANVIEN TO NV0001;
GRANT GIANGVIEN TO NV0002;
GRANT GIAOVU TO NV0003;
GRANT TRUONGDONVI TO NV0004;
GRANT TRUONGKHOA TO NV0005;

GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO NV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO NV0001;



GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO NV0002;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO NV0002;


GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO NV0003;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO NV0003;

GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO NV0004;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO NV0004;

GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO NV0005;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO NV0005;

GRANT SELECT,INSERT,UPDATE,DELETE ON SINHVIEN TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANSU TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON DONVI TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON HOCPHAN TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON KHMO TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON PHANCONG TO SV0001;
GRANT SELECT,INSERT,UPDATE,DELETE ON DANGKY TO SV0001;












