ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- tạo schema mới
--- Xoá nếu nó đã tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLTRUONGHOC CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -01918 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/
CREATE USER QLTRUONGHOC IDENTIFIED BY 123123;
GRANT ALL PRIVILEGES TO QLTRUONGHOC;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;
/
conn QLTRUONGHOC/123123;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET CURRENT_SCHEMA = QLTRUONGHOC;
/
--- drop all table
DECLARE
    TYPE table_array IS VARRAY(7) OF VARCHAR2(30);
    v_table_names table_array := table_array('NHANSU', 'SINHVIEN', 'DONVI', 'HOCPHAN', 'KHMO', 'PHANCONG', 'DANGKY');
    v_sql        VARCHAR2(100);
BEGIN
    FOR i IN 1 .. v_table_names.COUNT LOOP
        BEGIN
            v_sql := 'DROP TABLE ' || v_table_names(i) || ' CASCADE CONSTRAINTS';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;

/
--- create table
CREATE TABLE NHANSU
(
    MANV VARCHAR2(6) NOT NULL,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(3)CONSTRAINT CHK_PHAI CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR2(10),
    VAITRO NVARCHAR2(20) CONSTRAINT CHK_VAITRO CHECK (VAITRO IN ('Nhân viên cơ bản', 'Giảng viên', 'Giáo vụ', 'Trưởng đơn vị', 'Trưởng khoa')),
    MADV VARCHAR2(6),
    CONSTRAINT PK_NS
    PRIMARY KEY(MANV)
);

CREATE TABLE SINHVIEN
(
    MASV VARCHAR2(6) NOT NULL,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(3) CONSTRAINT CHK_PHAI2 CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT VARCHAR2(10),
    MACT VARCHAR2(6),
    MANGANH VARCHAR2(6),
    SOTCTL INT,
    DTBTL FLOAT,
    CONSTRAINT PK_SV
    PRIMARY KEY(MASV)
);

CREATE TABLE DONVI
(
    MADV VARCHAR2(6) NOT NULL,
    TENDV NVARCHAR2(30),
    TRGDV VARCHAR2(6),
    CONSTRAINT PK_DV
    PRIMARY KEY(MADV),
    CONSTRAINT FK_TRGDV
    FOREIGN KEY(TRGDV) REFERENCES NHANSU(MANV)
);

CREATE TABLE HOCPHAN
(
    MAHP VARCHAR2(6) NOT NULL,
    TENHP NVARCHAR2(30),
    SOTC INT,
    STLT INT,
    STTH INT,
    SOSVTD INT,
    MADV VARCHAR2(6),
    CONSTRAINT PK_HP
    PRIMARY KEY(MAHP),
    CONSTRAINT FK_DVPHUTRACH
    FOREIGN KEY(MADV) REFERENCES DONVI(MADV)  
);

CREATE TABLE KHMO
(
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    CONSTRAINT PK_KHMO
    PRIMARY KEY(MAHP,HK,NAM,MACT),
    CONSTRAINT FK_HPMO
    FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
);

CREATE TABLE PHANCONG 
(
    MAGV VARCHAR2(6) NOT NULL,
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    CONSTRAINT PK_PHANCONG
    PRIMARY KEY(MAGV,MAHP,HK,NAM,MACT),
    CONSTRAINT FK_PHANCONG_GV
    FOREIGN KEY(MAGV) REFERENCES NHANSU(MANV),
    CONSTRAINT FK_PHANCONG_KHMO
    FOREIGN KEY(MAHP,HK,NAM,MACT) REFERENCES KHMO(MAHP,HK,NAM,MACT)
    
);

CREATE TABLE DANGKY
(
    MASV VARCHAR2(6) NOT NULL,
    MAGV VARCHAR2(6) NOT NULL,
    MAHP VARCHAR2(6) NOT NULL,
    HK INT NOT NULL,
    NAM INT NOT NULL,
    MACT VARCHAR2(6) NOT NULL,
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    CONSTRAINT PK_DANGKY
    PRIMARY KEY(MASV,MAGV,MAHP,HK,NAM,MACT),
    CONSTRAINT FK_DANGKY_SV
    FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_PHANCONG
    FOREIGN KEY(MAGV,MAHP,HK,NAM,MACT) REFERENCES PHANCONG(MAGV,MAHP,HK,NAM,MACT)
)
------ các ràng buộc toàn vẹn



----- Add data from csv

INSERT ALL 
INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV0001', 'Trương Hoàng Nhân', 'Nam', TO_DATE('17-08-2003', 'DD-MM-YYYY'), 'KTX Khu B', '0971641280', 'ĐT', 'CNTT' ,120, 8.0)
INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV0002', 'Nguyễn Văn A', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 'KTX Khu B', '0971641282', 'ĐT','CNTT', 120, 7.1)
SELECT * FROM dual;

INSERT ALL
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0001', 'Nguyễn Quang Định', 'Nữ', TO_DATE('01-01-1971', 'DD-MM-YYYY'), 10000, '0971641280','Nhân viên cơ bản' ,'VPK')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0002', 'Trương Kim Liên', 'Nữ', TO_DATE('01-01-1971', 'DD-MM-YYYY'), 10000, '0971641280','Giảng viên' ,'CNPM')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0003', 'Lưu Kiến Đạt', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Giáo vụ', 'VPK')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0004', 'Lê Viết Đạt Trọng', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Trưởng đơn vị', 'HTTT')
INTO NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NV0005', 'Nguyễn Văn A', 'Nam', TO_DATE('01-01-2003', 'DD-MM-YYYY'), 10000, '0971641282','Trưởng khoa', 'KHMT')
SELECT * FROM dual;

-- DONVI
INSERT ALL
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('CNPM', 'Công nghệ phần mềm', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('HTTT', 'Hệ thống thông tin', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('KHMT', 'Khoa học máy tính', 'NV0004')
INTO DONVI (MADV, TENDV, TRGDV) VALUES ('MMT', 'Mạng máy tính và viễn thông', 'NV0004')
SELECT * FROM dual;

--HOCPHAN
INSERT ALL
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC001', 'Cơ sở dữ liệu', 4, 11, 0, 80 ,'HTTT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC002', 'Phát triển ứng dụng Web', 4, 11, 0, 80 ,'CNPM')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC003', 'Nhập môn khoa học dữ liệu', 4, 11, 0, 80 ,'KHMT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC004', 'Lập trình hướng đối tượng', 4, 11, 0, 80 ,'CNPM')
SELECT * FROM dual;
INSERT ALL
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC006', 'Phương pháp tính', 4, 11, 0, 80 ,'HTTT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC007', 'Đại số tuyến tính', 4, 11, 0, 80 ,'CNPM')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC008', 'Nhập môn lập trình', 4, 11, 0, 80 ,'KHMT')
INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('CSC009', 'Kỹ thuật lập trình', 4, 11, 0, 80 ,'CNPM')
SELECT * FROM dual;


--KHMO
INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC001', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC002', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC003', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC004', 1, 2024, 'ĐT')
SELECT * FROM dual;
INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC006', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC007', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC008', 1, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC009', 1, 2024, 'ĐT')
SELECT * FROM dual;

INSERT ALL
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC006', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC007', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC008', 2, 2024, 'ĐT')
INTO KHMO (MAHP, HK, NAM, MACT) VALUES ('CSC009', 2, 2024, 'ĐT')
SELECT * FROM dual;

--PHANCONG
INSERT ALL
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC001', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC002', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC003', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC004', 1, 2024, 'ĐT')
SELECT * FROM dual;

INSERT ALL
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC006', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC007', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC008', 1, 2024, 'ĐT')
INTO PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV0002', 'CSC009', 1, 2024, 'ĐT')
SELECT * FROM dual;

--DANGKY
INSERT ALL
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC001',1 ,2024, 'ĐT', 10 ,10,10,10)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC002',1 ,2024, 'ĐT', 9 ,9,9,9)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC003', 1,2024, 'ĐT', 10 ,9,9,10)
INTO DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH,DIEMQT ,DIEMCK ,DIEMTK) VALUES ('SV0001', 'NV0002', 'CSC004', 1,2024, 'ĐT', 10 ,9.5,9.5,10)
SELECT * FROM dual;


select * from HOCPHAN
CREATE OR REPLACE PROCEDURE CREATEUSER_TABLE_SINHVIEN
AS
    CURSOR CUR IS (SELECT MASV
                    FROM SINHVIEN
                    WHERE MASV NOT IN (SELECT USERNAME
                                        		      FROM ALL_USERS)
                    );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
            
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE CUR;
END;
/
EXECUTE CREATEUSER_TABLE_SINHVIEN;

CREATE ROLE SV;
GRANT SV TO SV0001;
GRANT SELECT ON SINHVIEN TO SV0001;
GRANT UPDATE(DT,DCHI) ON SINHVIEN TO SV0001;
GRANT SELECT ON HOCPHAN TO SV0001;
GRANT SELECT ON KHMO TO SV0001;
GRANT SELECT ON PHANCONG TO SV0001;
GRANT SELECT ON DANGKY TO SV0001;
select * from DANGKY
---------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE CREATEUSER_TABLE_NHANSU
AS
    CURSOR CUR IS (SELECT MANV
                    FROM NHANSU
                    WHERE MANV NOT IN (SELECT USERNAME
                                        		      FROM ALL_USERS)
                    );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
            
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE CUR;
END;
/
EXECUTE CREATEUSER_TABLE_NHANSU;

CREATE ROLE NVCB;
GRANT NVCB TO NV0001;
GRANT ALL PRIVILEGES TO NV0001;


CREATE ROLE GIANGVIEN;
GRANT GIANGVIEN TO NV0002;
GRANT ALL PRIVILEGES TO NV0002;

CREATE ROLE GIAOVU;
GRANT GIAOVU TO NV0003;
GRANT ALL PRIVILEGES TO NV0003;

CREATE ROLE TRUONGDONVI;
GRANT TRUONGDONVI TO NV0004;
GRANT ALL PRIVILEGES TO NV0004;

CREATE ROLE TRUONGKHOA;
GRANT TRUONGKHOA TO NV0005;
GRANT ALL PRIVILEGES TO NV0005;



UPDATE QLTRUONGHOC.PHANCONG SET HK = 2, NAM = 2025, MACT = 'CQ ' 
                            WHERE MAGV = 'NV0002' AND MAHP = 'CSC001';
